cook/urls.py
from django.urls import path
# from .views import 

urlpatterns = [
    # path('registr/', SignUpView.as_view(), name='registr'),
    # path('login/', LoginView.as_view(), name='login'),
    # path('main/', MainView.as_view(), name='main'),
    # path('logout/', logout_view, name='logout'),
]

manager/urls.py
from django.urls import path
from .views import manager, all_products, manage_pizza, manage_sushi, manage_sets, manage_buyers, manage_chefs, manage_managers, test

app_name = 'manager'

urlpatterns = [
    path('manager/', manager, name='manager_main'),

    path('manager/all_product/', all_products, name='all_products'),

    path('manager/Pizza_manage/', manage_pizza, name='manage_pizza'),
    path('manager/Sushi_manage', manage_sushi, name='manage_sushi'),
    path('manager/Sets_manage/', manage_sets, name='manage_setss'),

    path('manager/buyers/', manage_buyers, name='buyers'),
    path('manager/chefs/', manage_chefs, name='chefs'),
    path('manager/managers/', manage_managers, name='managers'),

    path('test', test, name='test')
]

pizzaproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from pizza_main_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='all_menu'),
    path('', include('pizza_main_app.urls')),
    path('', include('users.urls')),
    path('', include('manager.urls')),
    path('', include('cook.urls')),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import FormView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout
from pizza_main_app.models import Menu


def manager(request):
    page_title = 'Manager consol'
    drop_menu = Menu.objects.all()
    return render(request, 'main_manage.html', {'drop_items': drop_menu, 'global_title': page_title})

def all_products(request):
    page_title = 'Produktový management'
    drop_menu = Menu.objects.all()
    content = 'all products'
    return render(request, 'main_manage.html', {'drop_items': drop_menu, 'global_title': page_title, 'main_content': content})

def manage_pizza(request):
    page_title = 'Změny Pizza'
    drop_menu = Menu.objects.all()
    content = 'Změny Pizza'
    return render(request, 'main_manage.html', {'drop_items': drop_menu, 'global_title': page_title, 'main_content': content})

def manage_sushi(request):
    page_title = 'Změny Sushi'
    drop_menu = Menu.objects.all()
    content = 'Změny Sushi'
    return render(request, 'main_manage.html', {'drop_items': drop_menu, 'global_title': page_title, 'main_content': content})

def manage_sets(request):
    page_title = 'Změny Sets'
    drop_menu = Menu.objects.all()
    content = 'Změny Sets'
    return render(request, 'main_manage.html', {'drop_items': drop_menu, 'global_title': page_title, 'main_content': content})

def manage_buyers(request):
    page_title = 'Naši yákazíci'
    drop_menu = Menu.objects.all()
    content = 'Naši zákazíci'
    return render(request, 'main_manage.html', {'drop_items': drop_menu, 'global_title': page_title, 'main_content': content})

def manage_chefs(request):
    page_title = 'Naši kuchaři'
    drop_menu = Menu.objects.all()
    content = 'Naši kuchaři'
    return render(request, 'main_manage.html', {'drop_items': drop_menu, 'global_title': page_title, 'main_content': content})

def manage_managers(request):
    page_title = 'Naši manažeři'
    drop_menu = Menu.objects.all()
    content = 'Naši manažeři'
    return render(request, 'main_manage.html', {'drop_items': drop_menu, 'global_title': page_title, 'main_content': content})

class LoginManagerView(FormView):
    form_class = AuthenticationForm
    success_url = '/'
    template_name = 'registration/template_login.html'

    def form_valid(self, form):
        login(self.request, form.get_user())
        status = 'valid'
        return super().form_valid(form)

    def form_invalid(self, form):
        status = 'invalid'
        return redirect(reverse('registr'))
    
def logout_view(request):
    logout(request)
    return redirect('/')

def test(request):
    return render(request, 'loging_manage.html')

manager/templates/base_manager.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>{{global_title}}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/index.min.css' %}">
    <link rel="shortcut icon" href="{% static 'image/manage_favicon.jpg' %}">


</head>
<body>
    <header class="header">
        <div class="manage_title">
            <a class="navbar-brand manage_home_page" href="{% url 'all_menu' %}">
            <img
                src="{% static 'images/Pizza-logo.png' %}"
                alt="Logo"
                width="70"
            />
            <span class="manage_title">Pizza Shop</span>
            <img
                src="{% static 'images/Pizza-logo.png' %}"
                alt="Logo"
                width="70"
            />
            </a>
        </div>
    </header>
    <div class="container_main_manage">
    <nav class="navbar_wrap">
        <span class="manager_closing_menu"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M120-240v-80h520v80H120Zm664-40L584-480l200-200 56 56-144 144 144 144-56 56ZM120-440v-80h400v80H120Zm0-200v-80h520v80H120Z"/></svg></span>
        <ul class="manage_nav">
            <li class="nav-item-manage nav-tem-manage-product">
                <a class="nav-link-manage" aria-current="page" href="{% url 'manager:all_products' %}">Produkce</a>
                <ul class="manager_product_list">
                    {% for drop_item in drop_items %}
                    <li class="drop_product_list">
                        <a class="dropdown-item-manage" href="/manager/{{drop_item}}_manage">{{drop_item}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            <li class="nav-item-manage">
                <a class="nav-link-manage" href="{% url 'manager:buyers' %}">Zákazníci</a>
            </li>
            <li class="nav-item-manage">
                <a class="nav-link-manage" href="{% url 'manager:chefs' %}">Kuchaři</a>
            </li>
            <li class="nav-item-manage">
                <a class="nav-link-manage" href="{% url 'manager:managers' %}">Manažeři</a>
            </li>
        </ul>
    </nav> 
    <main class="main main-manage">
        {% block manage_content %}
        {% endblock manage_content %}
    </main>
</div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/manager.js' %}"></script>
</body>
</html>

manager/templates/loging_manage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loging manager</title>
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
    crossorigin="anonymous" />
    <link rel="stylesheet" href="../static/css/index.min.css" />
</head>
<body>
    <div class="manage_loging">
    <form>
        <div class="mb-3">
            <label for="exampleInputLogin" class="form-label">Login</label>
            <input type="text" class="form-control" id="exampleInputLogin" aria-describedby="emailLogin">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"            crossorigin="anonymous"></script>
</body>
</html>

manager/templates/main_manage.html
{% comment %} {% if user.is_authenticated  and user.user_type == 'manager'%}
{% include "base_manager.html" %}
{% block manage_content %}
    {{main_content}}
{% endblock manage_content %}
{% else %}
{% include "loging_manage.html" %}
{% endif %} {% endcomment %}

{% include "base_manager.html" %}
{% block manage_content %}
    {{main_content}}
{% endblock manage_content %}