cook/urls.py
from django.urls import path
# from .views import 

urlpatterns = [
    # path('registr/', SignUpView.as_view(), name='registr'),
    # path('login/', LoginView.as_view(), name='login'),
    # path('main/', MainView.as_view(), name='main'),
    # path('logout/', logout_view, name='logout'),
]

manager/urls.py
from django.urls import path
from .views import manager, all_products, manage_pizza, manage_sushi, manage_sets, manage_buyers, manage_chefs, manage_managers, test

app_name = 'manager'

urlpatterns = [
    path('manager/', manager, name='manager_main'),

    path('manager/all_product/', all_products, name='all_products'),

    path('manager/Pizza_manage/', manage_pizza, name='manage_pizza'),
    path('manager/Sushi_manage', manage_sushi, name='manage_sushi'),
    path('manager/Sets_manage/', manage_sets, name='manage_setss'),

    path('manager/buyers/', manage_buyers, name='buyers'),
    path('manager/chefs/', manage_chefs, name='chefs'),
    path('manager/managers/', manage_managers, name='managers'),

    path('test', test, name='test')
]

pizza_main_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from pizza_main_app import views

urlpatterns = [
    path('Pizza/', views.pizza, name='Pizza'),
    path('Sushi/', views.sushi, name='Sushi'),
    path('Sets/', views.sets, name='Sets'),
    path('All_menu/', views.home, name='all_menu'),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzaproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from pizza_main_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='all_menu'),
    path('', include('pizza_main_app.urls')),
    path('', include('users.urls')),
    path('', include('manager.urls')),
    path('', include('cook.urls')),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizza_main_app/models.py
from django.db import models


class Menu(models.Model):
    titles = models.CharField(max_length=10)

    def __str__(self):
        return self.titles

class Pizza(models.Model):
    title = models.CharField(max_length=100)
    ingredients = models.TextField()
    class_name = models.CharField(max_length=100, default='pizza')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image_product = models.ImageField(max_length=200)

    def __str__(self):
        return self.title

class Sushi(models.Model):
    title = models.CharField(max_length=100)
    ingredients = models.TextField()
    class_name = models.CharField(max_length=100, default='sushi')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image_product = models.ImageField(max_length=200)

    def __str__(self):
        return self.title

class Set(models.Model):
    title = models.CharField(max_length=100)
    ingredients = models.TextField()
    class_name = models.CharField(max_length=100, default='sets')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image_product = models.ImageField(max_length=200)

    def __str__(self):
        return self.title

pizza_main_app/forms.py
from django import forms

pizza_main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .models import Menu, Pizza, Sushi, Set

def sorting_list(lst: list, cols: int) -> list[list]:
    return [lst[i:i + cols] for i in range(0, len(lst), cols)]


def home(request):
    page_title = 'Pizza Shop'
    drop_menu = Menu.objects.all()
    pizza_all = Pizza.objects.all()
    sushi_all = Sushi.objects.all()
    sets_all = Set.objects.all()
    combined_all = list(pizza_all)+list(sushi_all)+list(sets_all)
    combined_result = sorting_list(combined_all, 3)
    return render(request, 'main.html', {'drop_items': drop_menu, 'combined_result': combined_result, 'global_title': page_title})

def pizza(request):
    page_title = 'All Pizza'
    drop_menu = Menu.objects.all()
    pizza_all = Pizza.objects.all()
    combined_result = sorting_list(pizza_all, 3)
    return render(request, 'main.html', {'drop_items': drop_menu, 'combined_result': combined_result, 'global_title': page_title})

def sushi(request):
    page_title = 'All Sushi'
    drop_menu = Menu.objects.all()
    sushi_all = Sushi.objects.all()
    combined_result = sorting_list(sushi_all, 3)
    return render(request, 'main.html', {'drop_items': drop_menu, 'combined_result': combined_result, 'global_title': page_title})

def sets(request):
    page_title = 'All Sets'
    drop_menu = Menu.objects.all()
    sets_all = Set.objects.all()
    combined_result = sorting_list(sets_all, 3)
    return render(request, 'main.html', {'drop_items': drop_menu, 'combined_result': combined_result, 'global_title': page_title})

pizza_main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous" />
        <link rel="stylesheet" href="../static/css/index.min.css" />
        <link
            rel="shortcut icon"
            href="../static/images/Pizza-logo.png"
            type="image/x-icon" />

        <title>{{global_title}}</title>
    </head>
    <body>
        <div class="loging_wrap">
            <div class="registerModal"><span class="close-button" onclick="close_modal()">✖</span></div>
        </div>
        
        <header>
            <div class="loging_header">
                {% if user.is_authenticated  and user.user_type == 'buyer'%}
                    <section class="loging_active">
                        <p class="header_title">
                            <span class="header_title_static">Vítejte, </span>
                            <span class="header_title_dinamic"> {{ user.username }}! </span>
                            <span class="header_title_static">Jak vám můžeme pomoci dnes?</span>                  
                        </p>
                        <a class="log_button log_button_logout" href="{% url 'logout' %}">Odhlásit se</a>
                    </section>
                {% else %}
                    <section class="loging">
                        <a class="log_button log_button_loging" type="button">Přihlásit se</a>
                        <a class="log_button log_button_singin" type="button" href="{% url 'registr' %}">Registrovat se</a>
                    </section>
                {% endif %}
            </div>
            <nav class="navbar navbar-expand-lg bg-warning">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'all_menu' %}"
                        ><img
                            src="../static/images/Pizza-logo.png"
                            alt="Logo"
                            width="70"
                    /></a>
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div
                        class="collapse navbar-collapse"
                        id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'all_menu' %}"
                                    >Domov</a
                                >
                            </li>

                            <li class="nav-item dropdown">
                                <a
                                    class="nav-link dropdown-toggle"
                                    href="#"
                                    role="button"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    Menu
                                </a>
                                <ul class="dropdown-menu">
                                    {% for drop_item in drop_items %}
                                    <li>
                                        <a class="dropdown-item" href="/{{drop_item}}"
                                            >{{drop_item}}</a
                                        >
                                    </li>
                                    {% endfor %}
                                    <li><hr class="dropdown-divider" /></li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'all_menu' %}"
                                            >Celé menu</a
                                        >
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <form class="d-flex" role="search">
                            <input
                                class="form-control me-2"
                                type="search"
                                placeholder="Search"
                                aria-label="Search" />
                            <button
                                class="btn btn-outline-success"
                                type="submit">
                                Search
                            </button>
                        </form>
                    </div>
                </div>
            </nav>
        </header>
        <main class="Main">
            {% block content %}
            {% endblock content %}
        </main>
        <footer class="Footer">
            <div class="footer-wrap">
                <section class="management_button manager_button">
                    <a class="management_button_a manager_a" href="{% url 'manager:manager_main' %}">Manažer</a>
                </section>
                <span class="footer-phone">+420705923491</span>
                <section class="management_button cook_button">
                    <a class="management_button_a cook_a" href="{% url 'manager:manager_main' %}">Kuchař</a>
                </section>
            </div>
        </footer>
        <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"            crossorigin="anonymous"></script>
        <script src="../static/js/numberic.js"></script>
        <script src="../static/js/registration.js"></script>
    </body>
</html>
        
        

pizza_main_app/templates/card_product.html
{% block card_content %}
{% for products in combined_result %}
<div class="card-group d-flex">
    {% for product in products %}<div class="card-item"><img
src="../../media/{{product.image_product}}/"
class="card-img-top"
alt="{{product.title}}" />
<div class="card-body">
<h5 class="card-title">{{product.title}}</h5>
<p class="card-text">{{product.ingredients|truncatechars_html:90}}</p>
<section class="cardFooter">
    <p class="price">
        <span class="priceContent">{{product.price}}</span
        ><span class="priceCurr">Kč</span>
    </p>
    <p class="number number{{product.title}}">
        <span class="number_button number_minus" data-product-title="{{ product.title }}">-</span>
        <span class="number_number number_number" data-product-title="{{ product.title }}">0</span>
        <span class="number_button number_plus" data-product-title="{{ product.title }}">+</span>
    </p>
</section>
<section class="cardFooter">
<a class="typeProduct" href="/{{product.class_name}}">{{product.class_name}}</a>
<button
type="button"
class="card-btn btn btn-primary"
data-product-title="{{ product.title }}">
Objednat
</button>
</section>
</div></div>
    {% endfor %}
</div>
{% endfor %}
{% endblock card_content %}

pizza_main_app/templates/main.html
{% extends "base.html" %}

{% block content %}
    {% include "card_product.html" %}
{% endblock content %}